### ISSUE TITLE
The game will crash after title screen when turn on "dumpTexture" 

### ISSUE THREAD

**Issue by wehnes** [Kimjio/imas-sc-prism-localify#1]
If change the config.json like this

> "dumpTexture": true,

When trying to enter the main screen after title screen, the game will crash at the "Now loading" screen.
If turn on "enableLogger", the log is below. (ID has been replaced with X)

> "16122204606560475717": "ご注意",
"16602203932920455428": "このアプリは無料で遊ぶことができますが、\n一部有料のコンテンツがあります。",
"8200087824813136465": "未成年（18歳未満）の方へ",
"14654503889735382736": "未成年の方が有料コンテンツを購入する場合は、\n必ず法定代理人（ご両親等）の同意を得てから購入してください。\nゲームの利用方法（利用時間等）は、保護者とよく相談して決めてください。<line-height=66%>\n</line-height>\n<sprite=3><color=#ff3300>ないようがわからないときは、おうちのひとにがめんをみせてください。</color>",
"12733591669989287464": "未成年の方が有料コンテンツを購入する場合は、
\n必ず法定代理人（ご両親等）の同意を得てから購入してください。
\nゲームの利用方法（利用時間等）は、保護者とよく相談して決めてください。<line-height=66%>
\n</line-height>
\n<sprite=3><color=#ff3300>ないようがわからないときは、おうちのひとにがめんをみせてください。</color>",
"12161031167551550910": "メニュー",
"9183470484276325871": "THE IDOLM@STER™& ©BANDAI NAMCO Entertainment Inc.\nDeveloped by Bandai Namco Studios Inc.",
"14172991284374932175": "THE IDOLM@STER™& ©Bandai Namco Entertainment Inc.\nDeveloped by Bandai Namco Studios Inc.",
"14500846657440183683": "TOUCH TO START",
"2807039446418477443": "TOUCH TO START",
"7234205098868903984": "Ver. 1.1.2",
"18434774329718873092": "ID: XXXXXXXX",
"575378865958763869": "0",
"5524102860582138967": "<size=20>新ガシャ登場！</size>",
"14183704782676467067": "<size=20>正月パック販売中</size>",
"571552565493346489": "4",
"577292016191472559": "2",
"1975468959090268993": "3,300",
"14545876235257580229": "あと 00:00",
"11092905957409423787": "<color=#FF3300>100</color>/100",
"13937491451797417915": "<color=#FF3300>10</color>/10",

There is also no crash report in "\AppData\Roaming\dmmgameplayer5\Crashpad\reports"

**Comment by namenemeko** [comment]
Same thing happened to me. How can I resolve this?
